---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: expressionist
webhooks:
- name: expressionist.nais.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
  clientConfig:

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: expressionist
  namespace: nais
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: expressionist
    spec:
      containers:
      - image: navikt/expressionist
        imagePullPolicy: Always
        name: expressionist
        ports:
          - name: https
            containerPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: expressionist-int
  namespace: nais
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: expressionist
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: expressionist
  namespace: nais
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ExternalName
  externalName: your.laptop.fqdn
