---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: expressionist
webhooks:
  - name: expressionist.nais.io
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "nais.io"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - alerts
    clientConfig:
      url: local.fqdn
      caBundle: ca-bundle
