---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: expressionist
  namespace: nais
  labels:
    app: expressionist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressionist
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: expressionist
    spec:
      serviceAccountName: expressionist
      containers:
      - name: expressionist
        image: {{ .image }}
        imagePullPolicy: Always
