apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: expressionist-selfsigned-issuer
  namespace: nais
  labels:
    app.kubernetes.io/instance: expressionist
    app.kubernetes.io/name: expressionist
spec:
  selfSigned: {}
