apiVersion: v1
kind: Service
metadata:
  name: expressionist
  namespace: nais
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: expressionist
