name: Build and deploy
on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}
jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout expressionist
        uses: actions/checkout@v2
      - run: |
          export version=$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)
          echo "IMAGE=${IMAGE}:${version}" >> $GITHUB_ENV
      - uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
      - uses: docker/build-push-action@v3
        if: github.ref != 'refs/heads/master'
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE }}

  nais-yaml:
    name: Release to nais-yaml
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          path: expressionist
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.NAIS_APP_ID }}
          repo: navikt/nais-yaml
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ steps.get-token.outputs.token }}
          path: nais-yaml
      - name: Update nais-yaml
        run: |
          cd expressionist
          export version=$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)

          cd ../nais-yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          sed -E -i "s#image: ${IMAGE}:.+#image: ${IMAGE}:${version}#" vars/global.yaml
          git add .
          git --no-pager diff --cached
          git commit --no-verify -a -m "Bump Expressionist to version ${version}"
          git push
