name: Build and deploy
on: push

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout expressionist
        uses: actions/checkout@v2
      - run: docker build -t docker.pkg.github.com/"$GITHUB_REPOSITORY"/expressionist:$(./version.sh) .
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - run: docker push docker.pkg.github.com/"$GITHUB_REPOSITORY"/expressionist:$(./version.sh)

  nais-yaml:
    name: Release to nais-yaml
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout expressionist
        uses: actions/checkout@v2
        with:
          path: expressionist
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.NAIS_YAML_TOKEN }}
          path: nais-yaml
      - name: Update nais-yaml
        run: |
          cd expressionist
          version=$(./version.sh)

          cd ../nais-yaml
          git config user.name expressionist-actions
          git config user.email expressionist-actions@github.com

          sed -E -i "s#image: docker.pkg.github.com/"$GITHUB_REPOSITORY"/expressionist:.+#image: docker.pkg.github.com/"$GITHUB_REPOSITORY"/expressionist:${version}#" vars/expressionist.yaml
          git add .
          git --no-pager diff --cached
          git commit -a -m "Bump Expressionist to version ${version}"
          git push
